'use client';
import { ChevronDown, ChevronRight, Flag } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import AppSidebar from '../AppSidebar';

const defaultRows=[
 {q:'Q1',topic:'Number operations',score:'1 / 1',state:'good',answer:'C. 13',correct:'C. 13',note:'Correct. You handled the negative-number powers accurately.'},
 {q:'Q2',topic:'Percentages',score:'1 / 1',state:'good',answer:'B. 20%',correct:'B. 20%',note:'Correct. You identified 8 as one fifth of 40.'},
 {q:'Q3',topic:'Decimal place value',score:'0 / 1',state:'bad',answer:'B. 114.445',correct:'A. 11.4445',note:'The decimal point moved one place too far. Estimate the answer first so the final place value is easier to check.'},
 {q:'Q4',topic:'Distributive property',score:'1 / 1',state:'good',answer:'A. 49 × 20',correct:'A. 49 × 20',note:'Correct. You factored out the common value efficiently.'},
 {q:'Q5',topic:'Percentages',score:'1 / 1',state:'good',answer:'B. 48',correct:'B. 48',note:'Correct.'},
 {q:'Q6',topic:'Sequences',score:'0 / 1',state:'bad',answer:'B. 9',correct:'C. 10',note:'You recognised the increasing pattern but selected the second-day value rather than the third-day value.'},
 {q:'Q7',topic:'Sets',score:'1 / 1',state:'good',answer:'D',correct:'D',note:'Correct. Both boundary values were included.'},
 {q:'Q8',topic:'Sets',score:'1 / 1',state:'good',answer:'D. 2³',correct:'D. 2³',note:'Correct.'},
 {q:'Q9',topic:'Sets',score:'0 / 1',state:'bad',answer:'A. A finite set',correct:'C. An infinite set',note:'Positive integers continue without an endpoint, so the set is infinite.'},
 {q:'Q10',topic:'Venn diagrams',score:'1 / 1',state:'good',answer:'C. 23',correct:'C. 23',note:'Correct use of n(A∪B)=n(A)+n(B)−n(A∩B).'},
];
export default function ResultsPage({navigate}){
 const [openQuestion,setOpenQuestion]=useState('Q3');const [demoReport,setDemoReport]=useState(null);
 useEffect(()=>{try{const value=localStorage.getItem('mycsecpal-demo-report');if(value)setDemoReport(JSON.parse(value))}catch{}},[]);
 const rows=useMemo(()=>demoReport?demoReport.questions.map((question)=>{const selectedIndex='ABCD'.indexOf(question.selectedAnswer);const correctIndex='ABCD'.indexOf(question.correctAnswer);return {q:`Q${question.number}`,topic:question.topic,score:question.correct?'1 / 1':'0 / 1',state:question.correct?'good':'bad',answer:question.selectedAnswer?`${question.selectedAnswer}. ${question.options[selectedIndex]}`:'No answer',correct:`${question.correctAnswer}. ${question.options[correctIndex]}`,note:question.correct?'Correct.':'Review the question and compare your selection with the correct option.'}}):defaultRows,[demoReport]);
 const score=demoReport?.score??41;const maxScore=demoReport?.maxScore??60;const answered=demoReport?.answered??60;const percentage=Math.round(score/maxScore*100);const timeSeconds=demoReport?.timeUsedSeconds??5040;const timeLabel=`${Math.floor(timeSeconds/3600)}h ${Math.floor(timeSeconds%3600/60)}m`;const completedDate=demoReport?new Date(demoReport.submittedAt).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'}):'12 July 2026';
 return <div className="app-shell"><AppSidebar active="practice" onNavigate={navigate}/><main className="app-main results-page"><header className="results-title"><div><p className="eyebrow">Attempt report {demoReport?`· ${demoReport.displayCode}`:''}</p><h1>Mathematics · Paper 1</h1><p>Completed {completedDate}</p></div><img src="/assets/math-pal.png" alt="Mathematics companion"/></header><section className="attempt-summary-card"><article><span>Score</span><strong>{score} <small>/ {maxScore}</small></strong><em>{percentage}%</em></article><article><span>Questions completed</span><strong>{answered} <small>/ {maxScore}</small></strong><em className={answered===maxScore?'positive':''}>{answered===maxScore?'Complete':`${maxScore-answered} unanswered`}</em></article><article><span>Time used</span><strong>{timeLabel}</strong><em>{Math.max(0,90-Math.ceil(timeSeconds/60))} minutes remaining</em></article></section>
 <section className="examiner-summary detailed-summary"><img src="/assets/ai-marking.png" alt="Examiner notes"/><div><p className="eyebrow">Examiner summary</p><h2>{demoReport?'Your demonstrator paper has been marked.':'A steady attempt with clear strengths—and a pattern worth fixing.'}</h2><p>{demoReport?`You answered ${answered} of ${maxScore} questions and scored ${percentage}%. This report proves the question-bank form, SVG rendering, answer capture, submission and review path end to end.`:'You completed all 60 questions in 1 hour 24 minutes and scored 68%. Your overall understanding is sound, but a few avoidable errors reduced your score.'}</p><ul className="examiner-keynotes"><li><strong>Result:</strong> {score} correct answers from {maxScore} questions.</li><li><strong>Completion:</strong> {answered} questions answered and {maxScore-answered} left unanswered.</li><li><strong>Visual questions:</strong> Diagram, graph, table and matrix questions were rendered from structured visual specifications.</li><li><strong>Content status:</strong> This first form is a demonstrator and still requires subject-review approval.</li><li><strong>Next step:</strong> Connect validated topic-level feedback and the production marking workflow.</li></ul></div></section>
 <div className="trend-row"><b>Topic trends</b><span className="green">↑ Algebra</span><span className="green">↑ Percentages</span><span className="yellow">→ Number operations</span><span className="red">↓ Place value</span><span className="blue">Sets — keep practicing</span></div>
 <section className="breakdown"><div className="breakdown-title"><h2>Question review</h2><select><option>All questions</option><option>Correct</option><option>Incorrect</option></select></div>{rows.map((row)=>{const open=openQuestion===row.q;return <div key={row.q} className={`breakdown-row paper1-review-row ${open?'expanded':''}`}><div className={`status-dot ${row.state}`}>{row.state==='good'?'✓':'×'}</div><b>{row.q}</b><span className="marks-total">{row.topic}</span><strong>{row.score}</strong><span>{row.state==='good'?'Correct':'Incorrect'}</span><button onClick={()=>setOpenQuestion(open?null:row.q)}>{open?'Hide details':'Review'} {open?<ChevronDown size={15}/>:<ChevronRight size={15}/>}</button>{open&&<div className="expanded-detail paper1-review-detail"><div className="answer-comparison"><p><span>Your answer</span><strong className={row.state==='good'?'correct-answer':'incorrect-answer'}>{row.answer}</strong></p><p><span>Correct answer</span><strong className="correct-answer">{row.correct}</strong></p></div><div className="what-happened"><h3>Examiner note</h3><p>{row.note}</p><button className="button outline small"><Flag size={15}/>Report an issue</button></div></div>}</div>})}</section></main></div>;
}
