export type PaperTwoRubric = { expected: string; criteria: string[]; graph?: { requiredPoints: Array<[number, number]>; tolerance: number } };

export const paperTwoRubrics: Record<string, PaperTwoRubric> = {
  "1a": { expected: "8.64 × 10^-4", criteria: ["8.64", "power of ten", "exponent -4"] },
  "1b": { expected: "$81,600", criteria: ["finds 15% or 85%", "subtracts the discount", "81,600"] },
  "1c": { expected: "4 years", criteria: ["uses I = PRT", "correct substitution", "t = 4", "states years"] },
  "2a": { expected: "x = 5", criteria: ["expands brackets", "collects terms", "x = 5"] },
  "2b": { expected: "5 students", criteria: ["union is 37", "subtracts from 42", "states 5"] },
  "2c": { expected: "98 cm²", criteria: ["uses trapezium formula", "correct substitution", "98 cm²"] },
  "2d": { expected: "4.2 km", criteria: ["multiplies by 50,000", "converts cm to km"] },
  "3a": { expected: "14", criteria: ["recognises increase by 3", "obtains 14", "completes table"] },
  "3b": { expected: "T = 3n + 2", criteria: ["coefficient 3", "constant 2"] },
  "3c": { expected: "77 tiles", criteria: ["substitutes n = 25", "obtains 77"] },
  "3d": { expected: "100 cannot occur because (100 - 2) / 3 is not an integer", criteria: ["uses 3n+2 = 100", "n is not whole"] },
  "4a": { expected: "(2x - 1)(x - 4)", criteria: ["correct factor pairs", "factorises completely", "correct final factors"] },
  "4b": { expected: "x = 1/2 or x = 4", criteria: ["uses factors", "sets factors to zero", "both roots"] },
  "4c": { expected: "12", criteria: ["f(2) = 3", "g(3) = 12"] },
  "4d": { expected: "turning point (2, -9); positive x-intercept (5, 0)", criteria: ["x = 2", "y = -9", "positive intercept x = 5", "coordinate notation"] },
  "5a": { expected: "15.0 cm", criteria: ["uses Pythagoras", "square root of 225", "15 cm to 3 sf"] },
  "5b": { expected: "15 cm", criteria: ["scale factor 25/15", "original shortest side 9", "15 cm"] },
  "5c": { expected: "14.2 km east", criteria: ["uses 18 sin 128°", "approximately 14.2", "east component"] },
  "6a": { expected: "2.3 books", criteria: ["Σfx = 69", "frequency 30", "2.3", "states books"] },
  "6b": { expected: "P = [[3],[1],[0]]", criteria: ["3 by 1 column matrix", "entries 3, 1, 0"] },
  "6c": { expected: "R = [[6,3,1],[4,5,1]] and RP = [[21],[17]]", criteria: ["correct R", "multiplies by P", "Team A 21", "Team B 17"] },
  "7a": { expected: "PQ = (6,4), QR = (3,2)", criteria: ["subtracts coordinates", "PQ (6,4)", "QR (3,2)"] },
  "7b": { expected: "collinear because QR = 1/2 PQ", criteria: ["compares vectors", "scalar multiple and conclusion"] },
  "7c": { expected: "10", criteria: ["uses ad-bc", "12-2", "10"] },
  "7d": { expected: "A^-1 = 1/10 [[3,-1],[-2,4]]", criteria: ["reciprocal determinant", "correct adjugate"] },
  "8a": { expected: "90°, angle in a semicircle", criteria: ["90 degrees", "angle-in-a-semicircle reason"] },
  "8b": { expected: "BC ≈ 12.4 cm", criteria: ["uses cosine rule", "correct substitution", "evaluates BC²", "about 12.4 cm"] },
  "8c": { expected: "245°", criteria: ["adds 180 degrees", "three-figure bearing"] },
  "9a": { expected: "4, 13, 28, 36, 40", criteria: ["13", "28", "36 and 40"] },
  "9b": { expected: "cumulative curve; median about 12.3 min", criteria: ["plots cumulative points", "suitable increasing curve", "uses CF 20", "median 12–13 min"], graph: { requiredPoints: [[5,4],[10,13],[15,28],[20,36],[25,40]], tolerance: 1.25 } },
  "9c": { expected: "240 m", criteria: ["first triangle 80", "rectangle 120", "final triangle 40", "adds areas", "240 m"] },
};
